import { PROGRAMMING_LANGUAGES } from "./enums";

export const SUPPORTED_PROGRAMMING_LANGUAGES = [
  PROGRAMMING_LANGUAGES.C,
  PROGRAMMING_LANGUAGES.CPP,
  PROGRAMMING_LANGUAGES.JAVA,
  PROGRAMMING_LANGUAGES.JAVASCRIPT,
  PROGRAMMING_LANGUAGES.PYTHON,
  PROGRAMMING_LANGUAGES.TYPESCRIPT,
];
